/**
 * ZkCred Managed Bindings — Bridge Index
 *
 * This file bridges the real Compact compiler output (src/managed/contract/)
 * with the rest of the ZkCred codebase.
 *
 * Generated by: compact compile contract/src/zkcred.compact src/managed/
 * Compiler: Compact 0.31.0 | Language: 0.23.0 | Runtime: 0.16.0
 *
 * DO NOT EDIT MANUALLY — re-run `compact compile` to regenerate.
 */

// Re-export everything from the real compiler output
export type {
  Witnesses,
  ImpureCircuits,
  ProvableCircuits,
  Ledger,
  Circuits as ContractCircuits,
} from "./contract/index.js";

export {
  Contract,
  ledger as decodeLedger,
  contractReferenceLocations,
  pureCircuits,
} from "./contract/index.js";

/**
 * LedgerState — maps to the generated Ledger type for use across the codebase.
 */
export interface LedgerState {
  minCreditScore: number;
  minAnnualIncome: bigint;
  minAge: number;
  isEligible: boolean;
  verificationCount: bigint;
  admin: Uint8Array;
}

/**
 * WitnessFunctions — private witness callbacks supplied by the DApp at runtime.
 * These NEVER leave the user's browser.
 */
export interface WitnessFunctions {
  getPrivateCreditScore: () => number;
  getPrivateAnnualIncome: () => bigint;
  getPrivateAge: () => number;
  getPrivateSalt: () => Uint8Array;
  getPrivateAdminKey: () => Uint8Array;
}

/**
 * Circuits — maps circuit names to their prover key file paths.
 * These are the REAL proving keys generated by the Compact compiler.
 */
export const Circuits = {
  initialize: "initialize",
  verifyEligibility: "verifyEligibility",
  updateThresholds: "updateThresholds",
  getEligibilityStatus: "getEligibilityStatus",
} as const;

export const ContractInfo = {
  name: "ZkCred",
  compilerVersion: "0.31.0",
  languageVersion: "0.23.0",
  runtimeVersion: "0.16.0",
  contractPath: "contract/src/zkcred.compact",
} as const;
